In [21]:
import numpy as np 
import pandas as pd 
import IPython

In [22]:
Matches = pd.read_csv('../input/la-liga-results-19952020/LaLiga_Matches_1995-2020.csv')
Matches

,Season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR
0,1995-96,2/9/1995,La Coruna,Valencia,3,0,H,2.0,0.0,H
1,1995-96,2/9/1995,Sp Gijon,Albacete,3,0,H,3.0,0.0,H
2,1995-96,3/9/1995,Ath Bilbao,Santander,4,0,H,2.0,0.0,H
3,1995-96,3/9/1995,Ath Madrid,Sociedad,4,1,H,1.0,1.0,D
4,1995-96,3/9/1995,Celta,Compostela,0,1,A,0.0,0.0,D
...,...,...,...,...,...,...,...,...,...,...
9659,2019-20,19/07/2020,Granada,Ath Bilbao,4,0,H,1.0,0.0,H
9660,2019-20,19/07/2020,Leganes,Real Madrid,2,2,D,1.0,1.0,D
9661,2019-20,19/07/2020,Levante,Getafe,1,0,H,0.0,0.0,D
9662,2019-20,19/07/2020,Osasuna,Mallorca,2,2,D,1.0,1.0,D
9663,2019-20,19/07/2020,Sevilla,Valencia,1,0,H,0.0,0.0,D

In [23]:
Matches.loc[Matches.FTHG > Matches.FTAG, "home_team_points"] = 3
Matches.loc[Matches.FTHG < Matches.FTAG, "away_team_points"] = 3
Matches.loc[Matches.FTHG == Matches.FTAG, "tie_points"] = 1

In [24]:
Home_win = Matches.loc[Matches.FTHG > Matches.FTAG][['Date','Season','HomeTeam','home_team_points']]
Away_win = Matches.loc[Matches.FTHG < Matches.FTAG][['Date','Season','AwayTeam','away_team_points']]
Home_tie = Matches.loc[Matches.FTHG == Matches.FTAG][['Date','Season','HomeTeam','tie_points']]
Away_tie = Matches.loc[Matches.FTHG == Matches.FTAG][['Date','Season','AwayTeam','tie_points']]

Home_win.columns = ['date','Season', 'team', 'points']
Away_win.columns = ['date','Season', 'team', 'points']
Home_tie.columns = ['date','Season', 'team', 'points']
Away_tie.columns = ['date','Season', 'team', 'points']

In [25]:
Points_over_time = pd.concat([Home_win,Away_win,Home_tie,Away_tie], ignore_index=True).sort_values('date', ascending = False)
Points_over_time
Points_over_time.head()

           date   Season         team  points
4101   9/9/2017  2017-18      Sevilla     3.0
9368   9/9/2017  2017-18  Real Madrid     1.0
4100   9/9/2017  2017-18    Barcelona     3.0
9369   9/9/2017  2017-18     Valencia     1.0
11820  9/9/2017  2017-18      Levante     1.0

In [26]:
Alltimeleague = Points_over_time.groupby(['team','Season']).points.sum().unstack().fillna(0).T.cumsum().T
Alltimeleague

Season,1995-96,1996-97,1997-98,1998-99,1999-2000,2000-01,2001-02,2002-03,2003-04,2004-05,...,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19,2019-20
team,,,,,,,,,,,,,,,,,,,,,
Alaves,0.0,0.0,0.0,40.0,101.0,150.0,204.0,239.0,239.0,239.0,...,278.0,278.0,278.0,278.0,278.0,278.0,333.0,380.0,430.0,469.0
Albacete,42.0,42.0,42.0,42.0,42.0,42.0,42.0,42.0,89.0,117.0,...,117.0,117.0,117.0,117.0,117.0,117.0,117.0,117.0,117.0,117.0
Almeria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,170.0,170.0,170.0,210.0,242.0,242.0,242.0,242.0,242.0,242.0
Ath Bilbao,48.0,112.0,177.0,237.0,287.0,330.0,383.0,438.0,494.0,545.0,...,836.0,885.0,930.0,1000.0,1055.0,1117.0,1180.0,1223.0,1276.0,1327.0
Ath Madrid,87.0,158.0,218.0,264.0,302.0,302.0,302.0,349.0,404.0,454.0,...,802.0,858.0,934.0,1024.0,1102.0,1190.0,1268.0,1347.0,1423.0,1493.0
Barcelona,80.0,170.0,244.0,323.0,387.0,450.0,514.0,570.0,642.0,726.0,...,1233.0,1324.0,1424.0,1511.0,1605.0,1696.0,1786.0,1879.0,1966.0,2048.0
Betis,62.0,139.0,198.0,247.0,289.0,289.0,348.0,402.0,454.0,516.0,...,687.0,734.0,790.0,815.0,815.0,860.0,899.0,959.0,1009.0,1050.0
Cadiz,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,36.0,36.0,36.0,36.0,36.0,36.0,36.0,36.0,36.0,36.0
Celta,52.0,101.0,161.0,225.0,278.0,337.0,397.0,458.0,497.0,497.0,...,600.0,600.0,637.0,686.0,737.0,797.0,842.0,891.0,932.0,969.0
Compostela,59.0,112.0,156.0,156.0,156.0,156.0,156.0,156.0,156.0,156.0,...,156.0,156.0,156.0,156.0,156.0,156.0,156.0,156.0,156.0,156.0
Cordoba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,20.0,20.0,20.0,20.0,20.0,20.0
Eibar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,35.0,78.0,132.0,183.0,230.0,272.0
Elche,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,40.0,81.0,81.0,81.0,81.0,81.0,81.0
Espanol,74.0,125.0,178.0,239.0,286.0,336.0,383.0,426.0,469.0,530.0,...,808.0,854.0,898.0,940.0,989.0,1032.0,1088.0,1137.0,1190.0,1215.0
Extremadura,0.0,44.0,44.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,...,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0
Getafe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47.0,...,344.0,391.0,438.0,480.0,517.0,553.0,553.0,608.0,667.0,721.0
Gimnastic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,28.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0,28.0
Girona,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.0,88.0,88.0
Granada,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,42.0,84.0,125.0,160.0,199.0,219.0,219.0,219.0,275.0
Hercules,0.0,41.0,41.0,41.0,41.0,41.0,41.0,41.0,41.0,41.0,...,76.0,76.0,76.0,76.0,76.0,76.0,76.0,76.0,76.0,76.0
Huesca,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.0,33.0
La Coruna,61.0,138.0,187.0,250.0,319.0,392.0,460.0,532.0,603.0,654.0,...,956.0,956.0,991.0,991.0,1026.0,1068.0,1104.0,1133.0,1133.0,1133.0
Las Palmas,0.0,0.0,0.0,0.0,0.0,46.0,86.0,86.0,86.0,86.0,...,86.0,86.0,86.0,86.0,86.0,130.0,169.0,191.0,191.0,191.0
Leganes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,35.0,78.0,123.0,159.0
Levante,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37.0,...,150.0,205.0,251.0,299.0,336.0,368.0,368.0,414.0,458.0,507.0
Logrones,0.0,33.0,33.0,33.0,33.0,33.0,33.0,33.0,33.0,33.0,...,33.0,33.0,33.0,33.0,33.0,33.0,33.0,33.0,33.0,33.0
Malaga,0.0,0.0,0.0,0.0,48.0,104.0,157.0,203.0,254.0,305.0,...,467.0,525.0,582.0,627.0,677.0,725.0,771.0,791.0,791.0,791.0
Mallorca,0.0,0.0,60.0,126.0,177.0,248.0,291.0,343.0,394.0,433.0,...,741.0,793.0,829.0,829.0,829.0,829.0,829.0,829.0,829.0,862.0
Merida,42.0,42.0,81.0,81.0,81.0,81.0,81.0,81.0,81.0,81.0,...,81.0,81.0,81.0,81.0,81.0,81.0,81.0,81.0,81.0,81.0
Murcia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,26.0,...,56.0,56.0,56.0,56.0,56.0,56.0,56.0,56.0,56.0,56.0
Numancia,0.0,0.0,0.0,0.0,45.0,84.0,84.0,84.0,84.0,113.0,...,148.0,148.0,148.0,148.0,148.0,148.0,148.0,148.0,148.0,148.0
Osasuna,0.0,0.0,0.0,0.0,0.0,42.0,84.0,131.0,179.0,225.0,...,515.0,569.0,608.0,647.0,647.0,647.0,669.0,669.0,669.0,721.0
Oviedo,48.0,96.0,136.0,181.0,226.0,267.0,267.0,267.0,267.0,267.0,...,267.0,267.0,267.0,267.0,267.0,267.0,267.0,267.0,267.0,267.0
Real Madrid,70.0,162.0,225.0,293.0,355.0,435.0,501.0,579.0,649.0,729.0,...,1226.0,1326.0,1411.0,1498.0,1590.0,1680.0,1773.0,1849.0,1917.0,2004.0
Recreativo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,36.0,36.0,36.0,...,167.0,167.0,167.0,167.0,167.0,167.0,167.0,167.0,167.0,167.0
Salamanca,33.0,33.0,78.0,105.0,105.0,105.0,105.0,105.0,105.0,105.0,...,105.0,105.0,105.0,105.0,105.0,105.0,105.0,105.0,105.0,105.0
Santander,47.0,97.0,142.0,184.0,230.0,269.0,269.0,313.0,356.0,400.0,...,681.0,708.0,708.0,708.0,708.0,708.0,708.0,708.0,708.0,708.0
Sevilla,48.0,91.0,91.0,91.0,119.0,119.0,172.0,222.0,277.0,337.0,...,731.0,781.0,831.0,894.0,970.0,1022.0,1094.0,1152.0,1211.0,1281.0
Sociedad,63.0,126.0,189.0,243.0,290.0,333.0,380.0,456.0,502.0,549.0,...,669.0,716.0,782.0,841.0,887.0,935.0,999.0,1048.0,1098.0,1154.0
Sp Gijon,46.0,96.0,109.0,109.0,109.0,109.0,109.0,109.0,109.0,109.0,...,239.0,276.0,276.0,276.0,276.0,315.0,346.0,346.0,346.0,346.0
Tenerife,72.0,128.0,173.0,207.0,207.0,207.0,245.0,245.0,245.0,245.0,...,281.0,281.0,281.0,281.0,281.0,281.0,281.0,281.0,281.0,281.0
Valencia,83.0,139.0,194.0,259.0,323.0,386.0,461.0,521.0,598.0,656.0,...,1046.0,1107.0,1172.0,1221.0,1298.0,1342.0,1388.0,1461.0,1522.0,1575.0
Valladolid,47.0,111.0,161.0,209.0,262.0,304.0,352.0,398.0,439.0,439.0,...,563.0,563.0,606.0,642.0,642.0,642.0,642.0,642.0,683.0,725.0
Vallecano,44.0,89.0,89.0,89.0,141.0,184.0,233.0,265.0,265.0,265.0,...,265.0,308.0,361.0,404.0,453.0,491.0,491.0,491.0,523.0,523.0
Villareal,0.0,0.0,0.0,36.0,36.0,36.0,36.0,36.0,36.0,36.0,...,36.0,36.0,36.0,36.0,36.0,36.0,36.0,36.0,36.0,36.0
Villarreal,0.0,0.0,0.0,0.0,0.0,57.0,100.0,145.0,199.0,264.0,...,643.0,684.0,684.0,743.0,803.0,867.0,934.0,995.0,1039.0,1099.0
Xerez,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0,34.0
Zaragoza,48.0,98.0,146.0,203.0,266.0,308.0,345.0,345.0,393.0,443.0,...,677.0,720.0,754.0,754.0,754.0,754.0,754.0,754.0,754.0,754.0

In [27]:
Alltimeleague.to_csv("All_time_league.csv")

In [33]:
iframe = "<iframe src='https://public.flourish.studio/visualisation/6430207/' style='width:100%;height:600px;'></iframe><div style='width:100%!;margin-top:4px!important;text-align:right!important;'><a class='flourish-credit' href='https://public.flourish.studio/visualisation/6430207/' target='_top' style='text-decoration:none!important'><img alt='Made with Flourish' src='https://public.flourish.studio/resources/made_with_flourish.svg' style='width:105px!important;height:16px!important;border:none!important;margin:0!important;'> </a></div>"
IPython.display.HTML(iframe)

In [ ]:
<div class="flourish-embed flourish-bar-chart-race" data-src="visualisation/6430207"><script src="https://public.flourish.studio/resources/embed.js"></script></div>